id: P010677
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:19:28.333311
source_metadata:
  id: bdr:W8723
  title: ཀུན་དགའ་ཆོས་ཀྱི་རྒྱ་མཚོའི་རྣམ་ཐར།
  author: ''
  volumes:
    2e7fc7d9f1ff40e4aee54340a2236851:
      image_group_id: I1KG9116
      title: ''
      volume_number: 1
      total_pages: 589
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
