id: I8EFE157E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T06:14:14+00:00'
last_modified: '2022-06-08T16:44:22.405388+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8723
  title: ཀུན་དགའ་ཆོས་ཀྱི་རྒྱ་མཚོའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    64FF:
      image_group_id: I1KG9116
      title: ''
      total_pages: 589
      order: 1
      base_file: 64FF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
