id: I8EFE157E
legacy_id: P010677
ocr_import_info:
  bdrc_scan_id: W8723
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T06:10:42'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:26:22.224611+00:00'
last_modified: 2022-09-04 11:26:37.268542
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8723
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW8723
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀུན་དགའ་ཆོས་ཀྱི་རྒྱ་མཚོའི་རྣམ་ཐར།
  author: དྲེའུ་ལྷས་གྲུབ་དབང ༠༢་ཀུན་དགའ་མི་འགྱུར་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.5873434123770207
  ocr_word_median_confidence_index: 0.5799999833106995
quality: null
bases:
  I1KG9116:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9116
      total_pages: 589
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9116.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5873434123770207
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
